### ISSUE TITLE
Oportunidades de mejora

### ISSUE THREAD

**Issue by enelramon** [YersonEscolastico/Solutions-scholastic-usuarios#1]
1. El nombre del Proyecto y el repositorio deben indicar algo mas parecido a su proyecto final. (**Algo como el nombre del sistema**)

**2. ****DAL**

2.1. No agregaste el script de la base de datos. (Favor agregarlo lo antes posible)

2.2. Recuerda que el nombre de la base de datos debería asemejarse al nombre del sistema.

2.3. El name space de la clase Contexto no deberia ser "namespace Registro.DAL.Scripts" es como si estuviera dentro de una carpeta scripts (Favor arreglar)

3. **BLL**

3.1. La asignación de la variable paso = true; no esta acorde con lo explicado en clases. Entiendo que tengas el error porque la diapositiva estaba incorrecta, pero recuerda que lo arregle y les explique.

4. **UI**

4.1. El nombre del formulario principal no deberia ser Form1

4.2. Necesito que cambies el nombre del registro a **rUsuarios** (UsuarioFormno esta acorde con el estándar de aplicada 1)

**Comment by YersonEscolastico** [comment]
Saludos profe ya arregle todos los issues que me indico arriva..
